version: '3.8'
services:
  reverse-proxy:
    image: nginx
    depends_on:
      - mock
      - swagger-ui
    ports:
      - 80:80
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.51.0
    ports: 
    - "8081:8080"
    environment:
    - SWAGGER_JSON=/opt/api/api-doc.yaml
    volumes:
    - ./api:/opt/api

  mock:
    image: stoplight/prism
    restart: always
    command: >
      mock -p 4010 --host 0.0.0.0
      /home/api/api-doc.yaml
    ports:
      - "4010:4010"
    volumes:
      - ./api:/home/api

  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root