export const CONSTANTS = {
    ACCOUNTS_TABLE_COL_BALANCE: 'Balance',
    ACCOUNTS_TABLE_COL_CREATED_AT: 'Created At',
    ACCOUNTS_TABLE_COL_ID: 'ID',
    ACCOUNTS_TABLE_COL_STATUS: 'Status',
    ACCOUNTS_TABLE_COL_UPDATED_AT: 'Updated At',
    ACCOUNTS_TABLE_TITLE: 'Accounts',
    ACCOUNTS_TABLE_TOOLBAR_TOTAL_NO_ACCOUNTS: 'Total # of accounts:',
    ACCOUNTS_TABLE_TOOLBAR_TOTAL_BALANCE: 'Total balance:',
    ERROR_SOMETHING_WENT_WRONG: 'Oops, something went wrong. Please try again later.',
    PROMPT_ARE_YOU_SURE: 'Are you sure you want to',
    SUCCESS: 'Success!',
    TOOLTIP_APPROVE_ACCOUNT: 'Approve Account',
    TOOLTIP_CLOSE_ACCOUNT: 'Close Account',
    TOOLTIP_FUND_ACCOUNT: 'Fund Account',
    TOOLTIP_REFRESH: 'Refresh Data',
    TOOLTIP_SUSPEND_ACCOUNT: 'Suspend Account',
}