import axios from "axios";

export const getAccounts = () => axios.get("/api/accounts/");

export const updateAccount = (payload) => {
    let id = payload._id;
    // Deleting the _id from payload as it is a read-only value generated by MongoDB. It should NOT be updated.
    delete payload._id;
    return axios.patch(`/api/accounts/${id}`, payload);
}